# Generated by Django 3.1.3 on 2020-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_url',
            field=models.URLField(blank=True),
        ),
    ]
