# Generated by Django 3.1.3 on 2020-11-29 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('liked_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('liked_user', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
